#! /bin/bash
if [ "$1" = "-h" ]; then
    echo "usage: $0 <node> [...]"
    echo "executes a command on the given node"
fi

NODE=`find /tmp/  2>/dev/null | grep pycore.*/n$1*$`

echo '# HOST:' ${f##*/}
vcmd -c $NODE -- sh -c "$(echo ${@:2})"
echo
