#!/bin/bash

TOTAL_NODES="$1"
TOTAL_ACTIVE_NODES="$2"
TIMEOUT_S="$3"
LATER=$((`date +%s` + $TIMEOUT_S))

while [ true ]; do
    # Check if test timed out
    if [ "$LATER" -lt `date +%s` ]; then
        echo "Watchagent on `hostname` waited successful." >&2
        killall python
        exit 0
    fi

    sleep 15
done
